command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "$DATABRICKS_APP_PORT"

env:
  - name: GENIE_SPACE_ID
    valueFrom: genie-space

  - name: VECTOR_SEARCH_INDEX_NAME
    valueFrom: vector-search-index

  - name: EMBEDDING_MODEL_NAME
    value: sentence-transformers/all-MiniLM-L6-v2

  - name: LLM_ENDPOINT_NAME
    value: databricks-gpt-oss-20b